# permissions for end users to edit operatorapplicationversions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorapplicationversion-editor-role
rules:
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplicationversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplicationversions/status
  verbs:
  - get
