# permissions for end users to view operatorapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorapplication-viewer-role
rules:
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplications/status
  verbs:
  - get
