
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - application.kubesphere.io
  resources:
  - manifests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubesphere.io
  resources:
  - manifests/finalizers
  verbs:
  - update
- apiGroups:
  - application.kubesphere.io
  resources:
  - manifests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplications/finalizers
  verbs:
  - update
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplicationversions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplicationversions/finalizers
  verbs:
  - update
- apiGroups:
  - application.kubesphere.io
  resources:
  - operatorapplicationversions/status
  verbs:
  - get
  - patch
  - update
