apiVersion: application.kubesphere.io/v1alpha1
kind: OperatorApplication
metadata:
  name: clickhouse
spec:
  # Add fields here
  name: "ClickHouse"
  description: "ClickHouse Database, the high performance columnar database."
  abstraction: |
    - 介绍
    - ClickHouse on QingCloud 是云化版本的ClickHouse集群应用
    - 兼容目前ClickHouse所有支持的数据引擎
    - 支持横向增加节点、集群节点升降配置等弹性功能
    - test text
  operator: "admin"
  icon: "https://github.com/etcd-io/etcd/raw/master/logos/etcd-glyph-color.svg"
  owner: "RadonDB"
status:
  latestVersion: "1.1.5[20.9]"
  state: active
