apiVersion: "clickhouse.radondb.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: ck-cluster
  namespace: ck-project
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeeper-server.ck-project
          port: 2181
        - host: zookeeper-1.zookeeper-server.ck-project
          port: 2181
        - host: zookeeper-2.zookeeper-server.ck-project
          port: 2181
    users:
      readonly/profile: readonly
      clickhouse/password: c1ickh0use0perator
      clickhouse/networks/ip:
        - 127.0.0.1
        - ::/0
      clickhouse/profile: default
      clickhouse/quotas: default
    profiles:
      readonly/readonly: "1"
      default/max_memory_usage: "1024000000"
    quotas:
      default/interval/duration: "3600"
    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1
    clusters:
      - name: all-nodes
        layout:
          shardsCount: 1
          replicasCount: 2

  defaults:
    templates:
      podTemplate: pod-template-with-volume
      dataVolumeClaimTemplate: data
      logVolumeClaimTemplate: data
      serviceTemplate: chi-svc-template

  templates:
    serviceTemplates:
      - name: chi-svc-template
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: NodePort

    podTemplates:
      - name: pod-template-with-volume
        metadata:
          annotations:
            backup.velero.io/backup-volumes: data
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: "clickhouse.radondb.com/chi"
                          operator: In
                          values:
                            - clickhouse
                    topologyKey: "kubernetes.io/hostname"
          containers:
            - name: clickhouse
              image: radondb/clickhouse-server:v21.1.3.32-stable
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: data
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "1G"
                  cpu: "0.5"
                limits:
                  memory: "1G"
                  cpu: "0.5"

    volumeClaimTemplates:
      - name: data
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi